In [1]:
import pandas as pd 
import requests

In [30]:
url = requests.get("https://api.themoviedb.org/3/movie/top_rated?api_key=c19efe31d5d02224c8eae1934a0b021f&language=en-US&page=1")

In [31]:
url.json()['results']

[{'adult': False,
  'backdrop_path': '/v5CEt88iDsuoMaW1Q5Msu9UZdEt.jpg',
  'genre_ids': [10749, 18],
  'id': 730154,
  'original_language': 'ja',
  'original_title': 'きみの瞳が問いかけている',
  'overview': "A tragic accident lead to Kaori's blindness, but she clings to life and the smaller pleasures it can still afford her. She meets Rui and begins to talk to him. Rui was once a promising kickboxer, but something happened in his past. Kaori's smile brings out a change in Rui. However, the two are connected in more than one way. Rui attempts to do what is right.",
  'popularity': 12.649,
  'poster_path': '/cVn8E3Fxbi8HzYYtaSfsblYC4gl.jpg',
  'release_date': '2020-10-23',
  'title': 'Your Eyes Tell',
  'video': False,
  'vote_average': 8.8,
  'vote_count': 224},
 {'adult': False,
  'backdrop_path': '/5hNcsnMkwU2LknLoru73c76el3z.jpg',
  'genre_ids': [35, 18, 10749],
  'id': 19404,
  'original_language': 'hi',
  'original_title': 'दिलवाले दुल्हनिया ले जायेंगे',
  'overview': 'Raj is a rich, carefree, happy-go-lucky second generation NRI. Simran is the daughter of Chaudhary Baldev Singh, who in spite of being an NRI is very strict about adherence to Indian values. Simran has left for India to be married to her childhood fiancé. Raj leaves for India with a mission at his hands, to claim his lady love under the noses of her whole family. Thus begins a saga.',
  'popularity': 32.973,
  'poster_path': '/2CAL2433ZeIihfX1Hb2139CX0pW.jpg',
  'release_date': '1995-10-20',
  'title': 'Dilwale Dulhania Le Jayenge',
  'video': False,
  'vote_average': 8.7,
  'vote_count': 3392},
 {'adult': False,
  'backdrop_path': '/iNh3BivHyg5sQRPP1KOkzguEX0H.jpg',
  'genre_ids': [18, 80],
  'id': 278,
  'original_language': 'en',
  'original_title': 'The Shawshank Redemption',
  'overview': 'Framed in the 1940s for the double murder of his wife and her lover, upstanding banker Andy Dufresne begins a new life at the Shawshank prison, where he puts his accounting skills to work for an amoral warden. During his long stretch in prison, Dufresne comes to be admired by the other inmates -- including an older prisoner named Red -- for his integrity and unquenchable sense of hope.',
  'popularity': 76.1,
  'poster_path': '/q6y0Go1tsGEsmtFryDOJo3dEmqu.jpg',
  'release_date': '1994-09-23',
  'title': 'The Shawshank Redemption',
  'video': False,
  'vote_average': 8.7,
  'vote_count': 20679},
 {'adult': False,
  'backdrop_path': '/rSPw7tgCH9c6NqICZef4kZjFOQ5.jpg',
  'genre_ids': [18, 80],
  'id': 238,
  'original_language': 'en',
  'original_title': 'The Godfather',
  'overview': 'Spanning the years 1945 to 1955, a chronicle of the fictional Italian-American Corleone crime family. When organized crime family patriarch, Vito Corleone barely survives an attempt on his life, his youngest son, Michael steps in to take care of the would-be killers, launching a campaign of bloody revenge.',
  'popularity': 85.757,
  'poster_path': '/eEslKSwcqmiNS6va24Pbxf2UKmJ.jpg',
  'release_date': '1972-03-14',
  'title': 'The Godfather',
  'video': False,
  'vote_average': 8.7,
  'vote_count': 15439},
 {'adult': False,
  'backdrop_path': '/jtAI6OJIWLWiRItNSZoWjrsUtmi.jpg',
  'genre_ids': [10749],
  'id': 724089,
  'original_language': 'en',
  'original_title': "Gabriel's Inferno Part II",
  'overview': "Professor Gabriel Emerson finally learns the truth about Julia Mitchell's identity, but his realization comes a moment too late. Julia is done waiting for the well-respected Dante specialist to remember her and wants nothing more to do with him. Can Gabriel win back her heart before she finds love in another's arms?",
  'popularity': 12.321,
  'poster_path': '/x5o8cLZfEXMoZczTYWLrUo1P7UJ.jpg',
  'release_date': '2020-07-31',
  'title': "Gabriel's Inferno Part II",
  'video': False,
  'vote_average': 8.6,
  'vote_count': 1378},
 {'adult': False,
  'backdrop_path': '/loRmRzQXZeqG78TqZuyvSlEQfZb.jpg',
  'genre_ids': [18, 36, 10752],
  'id': 424,
  'original_language': 'en',
  'original_title': "Schindler's List",
  'overview': 'The true story of how businessman Oskar Schindler saved over a thousand Jewish lives from the Nazis while they worked as slaves in his factory during World War II.',
  'popularity': 57.75,
  'poster_path': '/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg',
  'release_date': '1993-11-30',
  'title': "Schindler's List",
  'video': False,
  'vote_average': 8.6,
  'vote_count': 12348},
 {'adult': False,
  'backdrop_path': '/poec6RqOKY9iSiIUmfyfPfiLtvB.jpg',
  'genre_ids': [18, 80],
  'id': 240,
  'original_language': 'en',
  'original_title': 'The Godfather: Part II',
  'overview': 'In the continuing saga of the Corleone crime family, a young Vito Corleone grows up in Sicily and in 1910s New York. In the 1950s, Michael Corleone attempts to expand the family business into Las Vegas, Hollywood and Cuba.',
  'popularity': 56.971,
  'poster_path': '/v3KCBeX0CBlZnHZndimm7taYqwo.jpg',
  'release_date': '1974-12-20',
  'title': 'The Godfather: Part II',
  'video': False,
  'vote_average': 8.6,
  'vote_count': 9304},
 {'adult': False,
  'backdrop_path': '/w2uGvCpMtvRqZg6waC1hvLyZoJa.jpg',
  'genre_ids': [10749],
  'id': 696374,
  'original_language': 'en',
  'original_title': "Gabriel's Inferno",
  'overview': "An intriguing and sinful exploration of seduction, forbidden love, and redemption, Gabriel's Inferno is a captivating and wildly passionate tale of one man's escape from his own personal hell as he tries to earn the impossible--forgiveness and love.",
  'popularity': 11.514,
  'poster_path': '/oyG9TL7FcRP4EZ9Vid6uKzwdndz.jpg',
  'release_date': '2020-05-29',
  'title': "Gabriel's Inferno",
  'video': False,
  'vote_average': 8.6,
  'vote_count': 2194},
 {'adult': False,
  'backdrop_path': '/fQq1FWp1rC89xDrRMuyFJdFUdMd.jpg',
  'genre_ids': [10749, 35],
  'id': 761053,
  'original_language': 'en',
  'original_title': "Gabriel's Inferno Part III",
  'overview': "The final part of the film adaption of the erotic romance novel Gabriel's Inferno written by an anonymous Canadian author under the pen name Sylvain Reynard.",
  'popularity': 24.244,
  'poster_path': '/qtX2Fg9MTmrbgN1UUvGoCsImTM8.jpg',
  'release_date': '2020-11-19',
  'title': "Gabriel's Inferno Part III",
  'video': False,
  'vote_average': 8.6,
  'vote_count': 938},
 {'adult': False,
  'backdrop_path': '/mMtUybQ6hL24FXo0F3Z4j2KG7kZ.jpg',
  'genre_ids': [10749, 16, 18],
  'id': 372058,
  'original_language': 'ja',
  'original_title': '君の名は。',
  'overview': 'High schoolers Mitsuha and Taki are complete strangers living separate lives. But one night, they suddenly switch places. Mitsuha wakes up in Taki’s body, and he in hers. This bizarre occurrence continues to happen randomly, and the two must adjust their lives around each other.',
  'popularity': 167.115,
  'poster_path': '/q719jXXEzOoYaps6babgKnONONX.jpg',
  'release_date': '2016-08-26',
  'title': 'Your Name.',
  'video': False,
  'vote_average': 8.5,
  'vote_count': 8313},
 {'adult': False,
  'backdrop_path': '/l5K9elugftlcyIHHm4nylvsn26X.jpg',
  'genre_ids': [18],
  'id': 255709,
  'original_language': 'ko',
  'original_title': '소원',
  'overview': 'After 8-year-old So-won narrowly survives a brutal sexual assault, her family labors to help her heal while coping with their own rage and grief.',
  'popularity': 28.099,
  'poster_path': '/x9yjkm9gIz5qI5fJMUTfBnWiB2o.jpg',
  'release_date': '2013-10-02',
  'title': 'Hope',
  'video': False,
  'vote_average': 8.5,
  'vote_count': 305},
 {'adult': False,
  'backdrop_path': '/Ab8mkHmkYADjU7wQiOkia9BzGvS.jpg',
  'genre_ids': [16, 10751, 14],
  'id': 129,
  'original_language': 'ja',
  'original_title': '千と千尋の神隠し',
  'overview': 'A young girl, Chihiro, becomes trapped in a strange new world of spirits. When her parents undergo a mysterious transformation, she must call upon the courage she never knew she had to free her family.',
  'popularity': 99.81,
  'poster_path': '/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg',
  'release_date': '2001-07-20',
  'title': 'Spirited Away',
  'video': False,
  'vote_average': 8.5,
  'vote_count': 12381},
 {'adult': False,
  'backdrop_path': '/u1wHUA0R48FH4WV3sGqjwx3aNZm.jpg',
  'genre_ids': [16, 18, 10402, 10749],
  'id': 632632,
  'original_language': 'ja',
  'original_title': '映画 ギヴン',
  'overview': "The film centers on the love relationship among the band's bassist Haruki Nakayama, drummer Akihiko Kaji, and Akihiko's roommate and ex-boyfriend Ugetsu Murata.",
  'popularity': 131.827,
  'poster_path': '/xKCtoYHUyX8zAg68eemnYa2orep.jpg',
  'release_date': '2020-08-22',
  'title': 'Given',
  'video': False,
  'vote_average': 8.5,
  'vote_count': 291},
 {'adult': False,
  'backdrop_path': '/TU9NIjwzjoKPwQHoHshkFcQUCG.jpg',
  'genre_ids': [35, 53, 18],
  'id': 496243,
  'original_language': 'ko',
  'original_title': '기생충',
  'overview': "All unemployed, Ki-taek's family takes peculiar interest in the wealthy and glamorous Parks for their livelihood until they get entangled in an unexpected incident.",
  'popularity': 103.185,
  'poster_path': '/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg',
  'release_date': '2019-05-30',
  'title': 'Parasite',
  'video': False,
  'vote_average': 8.5,
  'vote_count': 13056},
 {'adult': False,
  'backdrop_path': '/1EAxNqdkVnp48a7NUuNBHGflowM.jpg',
  'genre_ids': [16, 28, 878, 18],
  'id': 283566,
  'original_language': 'ja',
  'original_title': 'シン・エヴァンゲリオン劇場版:||',
  'overview': 'In the aftermath of the Fourth Impact, stranded without their Evangelions, Shinji, Asuka, and Rei find refuge in one of the rare pockets of humanity that still exist on the ruined planet Earth. There, each of them live a life far different from their days as an Evangelion pilot. However, the danger to the world is far from over. A new impact is looming on the horizon—one that will prove to be the true end of Evangelion.',
  'popularity': 188.137,
  'poster_path': '/md5wZRRj8biHrGtyitgBZo7674t.jpg',
  'release_date': '2021-03-08',
  'title': 'Evangelion: 3.0+1.0 Thrice Upon a Time',
  'video': False,
  'vote_average': 8.5,
  'vote_count': 445},
 {'adult': False,
  'backdrop_path': '/qqHQsStV6exghCM7zbObuYBiYxw.jpg',
  'genre_ids': [18],
  'id': 389,
  'original_language': 'en',
  'original_title': '12 Angry Men',
  'overview': "The defense and the prosecution have rested and the jury is filing into the jury room to decide if a young Spanish-American is guilty or innocent of murdering his father. What begins as an open and shut case soon becomes a mini-drama of each of the jurors' prejudices and preconceptions about the trial, the accused, and each other.",
  'popularity': 28.654,
  'poster_path': '/ppd84D2i9W8jXmsyInGyihiSyqz.jpg',
  'release_date': '1957-04-10',
  'title': '12 Angry Men',
  'video': False,
  'vote_average': 8.5,
  'vote_count': 6150},
 {'adult': False,
  'backdrop_path': '/l6hQWH9eDksNJNiXWYRkWqikOdu.jpg',
  'genre_ids': [14, 18, 80],
  'id': 497,
  'original_language': 'en',
  'original_title': 'The Green Mile',
  'overview': "A supernatural tale set on death row in a Southern prison, where gentle giant John Coffey possesses the mysterious power to heal people's ailments. When the cell block's head guard, Paul Edgecomb, recognizes Coffey's miraculous gift, he tries desperately to help stave off the condemned man's execution.",
  'popularity': 64.806,
  'poster_path': '/velWPhVMQeQKcxggNEU8YmIo52R.jpg',
  'release_date': '1999-12-10',
  'title': 'The Green Mile',
  'video': False,
  'vote_average': 8.5,
  'vote_count': 13435},
 {'adult': False,
  'backdrop_path': '/nMKdUUepR0i5zn0y1T4CsSB5chy.jpg',
  'genre_ids': [18, 28, 80, 53],
  'id': 155,
  'original_language': 'en',
  'original_title': 'The Dark Knight',
  'overview': 'Batman raises the stakes in his war on crime. With the help of Lt. Jim Gordon and District Attorney Harvey Dent, Batman sets out to dismantle the remaining criminal organizations that plague the streets. The partnership proves to be effective, but they soon find themselves prey to a reign of chaos unleashed by a rising criminal mastermind known to the terrified citizens of Gotham as the Joker.',
  'popularity': 87.642,
  'poster_path': '/qJ2tW6WMUDux911r6m7haRef0WH.jpg',
  'release_date': '2008-07-14',
  'title': 'The Dark Knight',
  'video': False,
  'vote_average': 8.5,
  'vote_count': 26763},
 {'adult': False,
  'backdrop_path': '/suaEOtk1N1sgg2MTM7oZd2cfVp3.jpg',
  'genre_ids': [53, 80],
  'id': 680,
  'original_language': 'en',
  'original_title': 'Pulp Fiction',
  'overview': "A burger-loving hit man, his philosophical partner, a drug-addled gangster's moll and a washed-up boxer converge in this sprawling, comedic crime caper. Their adventures unfurl in three stories that ingeniously trip back and forth in time.",
  'popularity': 66.733,
  'poster_path': '/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg',
  'release_date': '1994-09-10',
  'title': 'Pulp Fiction',
  'video': False,
  'vote_average': 8.5,
  'vote_count': 22577},
 {'adult': False,
  'backdrop_path': '/lXhgCODAbBXL5buk9yEmTpOoOgR.jpg',
  'genre_ids': [12, 14, 28],
  'id': 122,
  'original_language': 'en',
  'original_title': 'The Lord of the Rings: The Return of the King',
  'overview': "Aragorn is revealed as the heir to the ancient kings as he, Gandalf and the other members of the broken fellowship struggle to save Gondor from Sauron's forces. Meanwhile, Frodo and Sam take the ring closer to the heart of Mordor, the dark lord's realm.",
  'popularity': 118.599,
  'poster_path': '/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg',
  'release_date': '2003-12-01',
  'title': 'The Lord of the Rings: The Return of the King',
  'video': False,
  'vote_average': 8.5,
  'vote_count': 19008}]

In [32]:
movie_rating=pd.DataFrame(response.json()['results'])[['id', 'title','overview','popularity','original_language','vote_average']]

In [33]:
movie_rating

,id,title,overview,popularity,original_language,vote_average
0,730154,Your Eyes Tell,"A tragic accident lead to Kaori's blindness, b...",12.649,ja,8.8
1,19404,Dilwale Dulhania Le Jayenge,"Raj is a rich, carefree, happy-go-lucky second...",32.973,hi,8.7
2,278,The Shawshank Redemption,Framed in the 1940s for the double murder of h...,76.100,en,8.7
3,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",85.757,en,8.7
4,724089,Gabriel's Inferno Part II,Professor Gabriel Emerson finally learns the t...,12.321,en,8.6
5,424,Schindler's List,The true story of how businessman Oskar Schind...,57.750,en,8.6
6,240,The Godfather: Part II,In the continuing saga of the Corleone crime f...,56.971,en,8.6
7,696374,Gabriel's Inferno,An intriguing and sinful exploration of seduct...,11.514,en,8.6
8,761053,Gabriel's Inferno Part III,The final part of the film adaption of the ero...,24.244,en,8.6
9,372058,Your Name.,High schoolers Mitsuha and Taki are complete s...,167.115,ja,8.5
10,255709,Hope,After 8-year-old So-won narrowly survives a br...,28.099,ko,8.5
11,129,Spirited Away,"A young girl, Chihiro, becomes trapped in a st...",99.810,ja,8.5
12,632632,Given,The film centers on the love relationship amon...,131.827,ja,8.5
13,496243,Parasite,"All unemployed, Ki-taek's family takes peculia...",103.185,ko,8.5
14,283566,Evangelion: 3.0+1.0 Thrice Upon a Time,"In the aftermath of the Fourth Impact, strande...",188.137,ja,8.5
15,389,12 Angry Men,The defense and the prosecution have rested an...,28.654,en,8.5
16,497,The Green Mile,A supernatural tale set on death row in a Sout...,64.806,en,8.5
17,155,The Dark Knight,Batman raises the stakes in his war on crime. ...,87.642,en,8.5
18,680,Pulp Fiction,"A burger-loving hit man, his philosophical par...",66.733,en,8.5
19,122,The Lord of the Rings: The Return of the King,Aragorn is revealed as the heir to the ancient...,118.599,en,8.5

In [34]:
movie_rating.shape

(20, 6)

In [29]:
# creating Empty dataframe 
df=pd.DataFrame()
df

Empty DataFrame
Columns: []
Index: []

In [36]:
for i in range (1,429):
    url = requests.get("https://api.themoviedb.org/3/movie/top_rated?api_key=c19efe31d5d02224c8eae1934a0b021f&language=en-US&page={}".format(i))  
    mov_df=pd.DataFrame(response.json()['results'])[['id', 'title','overview','popularity','original_language','vote_average']] 
    df=df.append(mov_df,ignore_index=True)

In [37]:
df

,id,title,overview,popularity,original_language,vote_average
0,730154,Your Eyes Tell,"A tragic accident lead to Kaori's blindness, b...",12.649,ja,8.8
1,19404,Dilwale Dulhania Le Jayenge,"Raj is a rich, carefree, happy-go-lucky second...",32.973,hi,8.7
2,278,The Shawshank Redemption,Framed in the 1940s for the double murder of h...,76.100,en,8.7
3,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",85.757,en,8.7
4,724089,Gabriel's Inferno Part II,Professor Gabriel Emerson finally learns the t...,12.321,en,8.6
...,...,...,...,...,...,...
8555,389,12 Angry Men,The defense and the prosecution have rested an...,28.654,en,8.5
8556,497,The Green Mile,A supernatural tale set on death row in a Sout...,64.806,en,8.5
8557,155,The Dark Knight,Batman raises the stakes in his war on crime. ...,87.642,en,8.5
8558,680,Pulp Fiction,"A burger-loving hit man, his philosophical par...",66.733,en,8.5
8559,122,The Lord of the Rings: The Return of the King,Aragorn is revealed as the heir to the ancient...,118.599,en,8.5

In [38]:
df.shape

(8560, 6)

In [39]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8560 entries, 0 to 8559
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 8560 non-null   int64
 1   title              8560 non-null   object
 2   overview           8560 non-null   object
 3   popularity         8560 non-null   float64
 4   original_language  8560 non-null   object
 5   vote_average       8560 non-null   float64
dtypes: float64(2), int64(1), object(3)
memory usage: 401.4+ KB

In [40]:
df.sample(10)

,id,title,overview,popularity,original_language,vote_average
6249,372058,Your Name.,High schoolers Mitsuha and Taki are complete s...,167.115,ja,8.5
7231,129,Spirited Away,"A young girl, Chihiro, becomes trapped in a st...",99.810,ja,8.5
3312,632632,Given,The film centers on the love relationship amon...,131.827,ja,8.5
3099,122,The Lord of the Rings: The Return of the King,Aragorn is revealed as the heir to the ancient...,118.599,en,8.5
3552,632632,Given,The film centers on the love relationship amon...,131.827,ja,8.5
7227,696374,Gabriel's Inferno,An intriguing and sinful exploration of seduct...,11.514,en,8.6
7296,497,The Green Mile,A supernatural tale set on death row in a Sout...,64.806,en,8.5
2811,129,Spirited Away,"A young girl, Chihiro, becomes trapped in a st...",99.810,ja,8.5
7761,19404,Dilwale Dulhania Le Jayenge,"Raj is a rich, carefree, happy-go-lucky second...",32.973,hi,8.7
4138,680,Pulp Fiction,"A burger-loving hit man, his philosophical par...",66.733,en,8.5

In [41]:
df.isna().sum()

id                   0
title                0
overview             0
popularity           0
original_language    0
vote_average         0
dtype: int64

In [42]:
df.describe()

                 id   popularity  vote_average
count    8560.00000  8560.000000   8560.000000
mean   248721.70000    72.744300      8.570000
std    301298.24703    49.667771      0.090005
min       122.00000    11.514000      8.500000
25%       268.50000    28.515250      8.500000
50%     10042.00000    65.769500      8.500000
75%    530340.25000   100.653750      8.600000
max    761053.00000   188.137000      8.800000

In [44]:
df.corr()

                    id  popularity  vote_average
id            1.000000   -0.197395      0.171560
popularity   -0.197395    1.000000     -0.478779
vote_average  0.171560   -0.478779      1.000000

In [46]:
df.to_csv('moviesdata_csv')